name: Test

on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}